### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by FluffyDiscord** [Moe-Net/Waifu-SR#2]
Hello, how can I use this upscaler. Where do I enter commands and run it in Wolfram Mathematica?

**Comment by oovm** [comment]
In https://github.com/Moe-Net/Waifu-SR/tree/master/Models

- `*.nb` define the interface function
- `*.WMLF` are the models

For example, if you wan't to use `LapSRN`, you just download these in one directory.

https://github.com/Moe-Net/Waifu-SR/blob/master/Models/Waifu-LapSRN.nb
https://github.com/Moe-Net/Waifu-SR/blob/master/Models/Waifu-LapSRN2x.WMLF
https://github.com/Moe-Net/Waifu-SR/blob/master/Models/Waifu-LapSRN4x.WMLF

**Comment by oovm** [comment]
In fact, here is the development branch of the project.

The main project is this: https://github.com/Moe-Net/Waifu-X

**Comment by FluffyDiscord** [comment]
Alright, I tried run it, but I got `NetReplacePart` error. (NetReplacePart::netarg1)

![screenshot_6](https://user-images.githubusercontent.com/10332247/45309052-2429c480-b523-11e8-8ead-8924ca746d21.jpg)

**Comment by oovm** [comment]
I think there should be a progressing bar. It shows downloading status.

`WaifuX` will automatically download the models.

Anyway, manually download and use LapSRN above.
